const categoryStyles = {
  politica: {
    text: "text-red-500",
    background: "bg-red-100",
    border: "border-red-500",
    font: "font-bold",
    padding: "p-4",
    rounded: "rounded-lg",
    shadow: "shadow-lg",
  },
  economia: {
    text: "text-green-500",
    background: "bg-green-100",
    border: "border-green-500",
    font: "font-semibold",
    padding: "p-4",
    rounded: "rounded-lg",
    shadow: "shadow-md",
  },
  sociedad: {
    text: "text-blue-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  deportes: {
    text: "text-red-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  cultura: {
    text: "text-blue-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  turismo: {
    text: "text-colorBlue1",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  transporte: {
    text: "text-blue-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  salud: {
    text: "text-green-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  ciencia: {
    text: "text-blue-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },
  educacion: {
    text: "text-blue-500",
    background: "bg-blue-100",
    border: "border-blue-500",
    font: "font-light",
    padding: "p-4",
    rounded: "rounded-md",
    shadow: "shadow-sm",
  },

  // Agrega más categorías según sea necesario...
};

export default categoryStyles;
